import { createPlaceResolver } from "@/lib/ruta-engine/place-resolver";
import type {
  RoutePlaceAliasRow,
  RoutePlaceRow,
  RouteRecord,
  RouteStopRow,
  RouteVariantMapRefRow,
  RouteVariantRow,
  RouteVariantStopOrderRow,
} from "@/lib/ruta-engine/types";

export const placeRows: RoutePlaceRow[] = [
  {
    id: "place-city",
    canonical_name: "Cebu City",
    city: "Cebu",
    latitude: 10.3157,
    longitude: 123.8854,
    source: "test",
    type: "city",
    barangay: null,
    parent_place_id: null,
    importance_rank: 100,
    related_place_ids: [],
    normalized_name: "cebu city",
  },
  {
    id: "place-lahug",
    canonical_name: "Lahug",
    city: "Cebu",
    latitude: 10.3338,
    longitude: 123.9032,
    source: "test",
    type: "district",
    barangay: "Lahug",
    parent_place_id: "place-city",
    importance_rank: 90,
    related_place_ids: [],
    normalized_name: "lahug",
  },
  {
    id: "place-apas",
    canonical_name: "Apas",
    city: "Cebu",
    latitude: 10.337,
    longitude: 123.908,
    source: "test",
    type: "district",
    barangay: "Apas",
    parent_place_id: "place-city",
    importance_rank: 82,
    related_place_ids: ["place-itpark"],
    normalized_name: "apas",
  },
  {
    id: "place-itpark",
    canonical_name: "IT Park",
    city: "Cebu",
    latitude: 10.3296,
    longitude: 123.9067,
    source: "test",
    type: "district",
    barangay: "Lahug",
    parent_place_id: "place-lahug",
    importance_rank: 95,
    related_place_ids: ["place-ayala"],
    normalized_name: "it park",
  },
  {
    id: "place-ayala",
    canonical_name: "Ayala",
    city: "Cebu",
    latitude: 10.3173,
    longitude: 123.9058,
    source: "test",
    type: "mall",
    barangay: null,
    parent_place_id: "place-city",
    importance_rank: 95,
    related_place_ids: ["place-itpark"],
    normalized_name: "ayala",
  },
  {
    id: "place-usc-main",
    canonical_name: "University of San Carlos Main Campus",
    city: "Cebu",
    latitude: 10.2974,
    longitude: 123.8997,
    source: "test",
    type: "school",
    barangay: null,
    parent_place_id: "place-city",
    importance_rank: 92,
    related_place_ids: [],
    normalized_name: "university of san carlos main campus",
  },
  {
    id: "place-colon",
    canonical_name: "Colon",
    city: "Cebu",
    latitude: 10.2955,
    longitude: 123.9023,
    source: "test",
    type: "district",
    barangay: null,
    parent_place_id: "place-city",
    importance_rank: 94,
    related_place_ids: [],
    normalized_name: "colon",
  },
  {
    id: "place-carbon",
    canonical_name: "Carbon",
    city: "Cebu",
    latitude: 10.2921,
    longitude: 123.8986,
    source: "test",
    type: "terminal",
    barangay: null,
    parent_place_id: "place-city",
    importance_rank: 94,
    related_place_ids: [],
    normalized_name: "carbon",
  },
  {
    id: "place-emall",
    canonical_name: "Elizabeth Mall",
    city: "Cebu",
    latitude: 10.2978,
    longitude: 123.8932,
    source: "test",
    type: "mall",
    barangay: null,
    parent_place_id: "place-city",
    importance_rank: 80,
    related_place_ids: [],
    normalized_name: "elizabeth mall",
  },
  {
    id: "place-nbt",
    canonical_name: "North Bus Terminal",
    city: "Cebu",
    latitude: 10.3205,
    longitude: 123.9188,
    source: "test",
    type: "terminal",
    barangay: null,
    parent_place_id: "place-city",
    importance_rank: 88,
    related_place_ids: [],
    normalized_name: "north bus terminal",
  },
  {
    id: "place-sm",
    canonical_name: "SM City Cebu",
    city: "Cebu",
    latitude: 10.3111,
    longitude: 123.918,
    source: "test",
    type: "mall",
    barangay: null,
    parent_place_id: "place-city",
    importance_rank: 95,
    related_place_ids: [],
    normalized_name: "sm city cebu",
  },
  {
    id: "place-parkmall",
    canonical_name: "Parkmall",
    city: "Mandaue",
    latitude: 10.3307,
    longitude: 123.9372,
    source: "test",
    type: "terminal",
    barangay: null,
    parent_place_id: null,
    importance_rank: 92,
    related_place_ids: [],
    normalized_name: "parkmall",
  },
];

export const aliasRows: RoutePlaceAliasRow[] = [
  {
    alias: "it park",
    normalized_alias: "it park",
    alias_kind: "short_name",
    confidence_score: 1,
    place_id: "place-itpark",
    route_places: {
      id: "place-itpark",
      canonical_name: "IT Park",
      normalized_name: "it park",
      city: "Cebu",
      barangay: "Lahug",
      type: "district",
      parent_place_id: "place-lahug",
      importance_rank: 95,
      related_place_ids: ["place-ayala"],
      latitude: 10.3296,
      longitude: 123.9067,
    },
  },
  {
    alias: "ayala",
    normalized_alias: "ayala",
    alias_kind: "short_name",
    confidence_score: 1,
    place_id: "place-ayala",
    route_places: {
      id: "place-ayala",
      canonical_name: "Ayala",
      normalized_name: "ayala",
      city: "Cebu",
      barangay: null,
      type: "mall",
      parent_place_id: "place-city",
      importance_rank: 95,
      related_place_ids: ["place-itpark"],
      latitude: 10.3173,
      longitude: 123.9058,
    },
  },
  {
    alias: "usc main",
    normalized_alias: "usc main",
    alias_kind: "abbreviation",
    confidence_score: 1,
    place_id: "place-usc-main",
    route_places: {
      id: "place-usc-main",
      canonical_name: "University of San Carlos Main Campus",
      normalized_name: "university of san carlos main campus",
      city: "Cebu",
      barangay: null,
      type: "school",
      parent_place_id: "place-city",
      importance_rank: 92,
      related_place_ids: [],
      latitude: 10.2974,
      longitude: 123.8997,
    },
  },
  {
    alias: "metro gaisano colon",
    normalized_alias: "metro gaisano colon",
    alias_kind: "landmark",
    confidence_score: 0.9,
    place_id: "place-colon",
    route_places: {
      id: "place-colon",
      canonical_name: "Colon",
      normalized_name: "colon",
      city: "Cebu",
      barangay: null,
      type: "district",
      parent_place_id: "place-city",
      importance_rank: 94,
      related_place_ids: [],
      latitude: 10.2955,
      longitude: 123.9023,
    },
  },
  {
    alias: "e mall",
    normalized_alias: "e mall",
    alias_kind: "short_name",
    confidence_score: 1,
    place_id: "place-emall",
    route_places: {
      id: "place-emall",
      canonical_name: "Elizabeth Mall",
      normalized_name: "elizabeth mall",
      city: "Cebu",
      barangay: null,
      type: "mall",
      parent_place_id: "place-city",
      importance_rank: 80,
      related_place_ids: [],
      latitude: 10.2978,
      longitude: 123.8932,
    },
  },
  {
    alias: "emall",
    normalized_alias: "emall",
    alias_kind: "short_name",
    confidence_score: 1,
    place_id: "place-emall",
    route_places: {
      id: "place-emall",
      canonical_name: "Elizabeth Mall",
      normalized_name: "elizabeth mall",
      city: "Cebu",
      barangay: null,
      type: "mall",
      parent_place_id: "place-city",
      importance_rank: 80,
      related_place_ids: [],
      latitude: 10.2978,
      longitude: 123.8932,
    },
  },
  {
    alias: "north bus terminal",
    normalized_alias: "north bus terminal",
    alias_kind: "short_name",
    confidence_score: 1,
    place_id: "place-nbt",
    route_places: {
      id: "place-nbt",
      canonical_name: "North Bus Terminal",
      normalized_name: "north bus terminal",
      city: "Cebu",
      barangay: null,
      type: "terminal",
      parent_place_id: "place-city",
      importance_rank: 88,
      related_place_ids: [],
      latitude: 10.3205,
      longitude: 123.9188,
    },
  },
  {
    alias: "sm hypermarket",
    normalized_alias: "sm hypermarket",
    alias_kind: "landmark",
    confidence_score: 0.8,
    place_id: "place-sm",
    route_places: {
      id: "place-sm",
      canonical_name: "SM City Cebu",
      normalized_name: "sm city cebu",
      city: "Cebu",
      barangay: null,
      type: "mall",
      parent_place_id: "place-city",
      importance_rank: 95,
      related_place_ids: [],
      latitude: 10.3111,
      longitude: 123.918,
    },
  },
  {
    alias: "parkmall puj terminal",
    normalized_alias: "parkmall puj terminal",
    alias_kind: "terminal",
    confidence_score: 1,
    place_id: "place-parkmall",
    route_places: {
      id: "place-parkmall",
      canonical_name: "Parkmall",
      normalized_name: "parkmall",
      city: "Mandaue",
      barangay: null,
      type: "terminal",
      parent_place_id: null,
      importance_rank: 92,
      related_place_ids: [],
      latitude: 10.3307,
      longitude: 123.9372,
    },
  },
];

export const routeRows: RouteRecord[] = [
  {
    dataset_name: "cebu_jeepney_routes",
    code: "17B",
    label: "17B",
    route_name: "Apas to Carbon",
    origin: "Apas",
    destination: "Carbon",
    qa_status: "high_confidence",
    completeness_score: 92,
    source_urls: ["https://example.com/17b"],
    roads: ["Gorordo Ave", "Magallanes St"],
    schools: ["University of San Carlos Main Campus"],
    malls_groceries: ["Ayala", "Elizabeth Mall"],
    churches: [],
    government: [],
    hotels: [],
    health: [],
    terminals: ["Carbon"],
    info: [
      "Apas - IT Park - Ayala - University of San Carlos Main Campus - Colon - Carbon",
    ],
    raw_sections: {
      info: "Apas - IT Park - Ayala - University of San Carlos Main Campus - Colon - Carbon",
    },
    warnings: [],
    imported_at: "2026-04-20T00:00:00.000Z",
  },
];

export const variantRows: RouteVariantRow[] = [
  {
    id: "variant-17b",
    dataset_name: "cebu_jeepney_routes",
    route_code: "17B",
    variant_key: "17b_apas_carbon_outbound",
    display_name: "Apas to Carbon",
    direction: "outbound",
    signboard: "Apas - Carbon",
    origin_place_id: "place-apas",
    destination_place_id: "place-carbon",
    qa_status: "high_confidence",
    confidence_score: 0.92,
    source_urls: ["https://example.com/17b"],
    warnings: [],
    raw_summary: {
      route_name: "Apas to Carbon",
      origin: "Apas",
      destination: "Carbon",
    },
    imported_at: "2026-04-20T00:00:00.000Z",
  },
];

export const mapRefRows: RouteVariantMapRefRow[] = [
  {
    id: "mapref-17b",
    variant_id: "variant-17b",
    page_url: "https://cebujeepneys.weebly.com/17b.html",
    google_map_url: "https://maps.google.com/?msid=abc123",
    embed_url: "https://maps.google.com/maps/ms?msa=0&msid=abc123&output=embed",
    map_id: "abc123",
    center_ll: "10.31,123.90",
    span: "0.01,0.02",
    iwloc: "000",
    map_title: "17B route",
    source: "cebujeepneys.weebly.com",
    created_at: "2026-04-20T00:00:00.000Z",
  },
];

export const stopRows: RouteStopRow[] = [
  ["stop-apas", "Apas", "place-apas"],
  ["stop-itpark", "IT Park", "place-itpark"],
  ["stop-ayala", "Ayala", "place-ayala"],
  ["stop-usc-main", "University of San Carlos Main Campus", "place-usc-main"],
  ["stop-colon", "Colon", "place-colon"],
  ["stop-carbon", "Carbon", "place-carbon"],
].map(([id, canonicalName, placeId]) => ({
  id,
  canonical_name: canonicalName,
  display_name: canonicalName,
  place_id: placeId,
  latitude: null,
  longitude: null,
  stop_type: "stop",
  city: "Cebu",
  barangay: null,
  source: "test",
  created_at: "2026-04-20T00:00:00.000Z",
}));

export const stopOrderRows: RouteVariantStopOrderRow[] = [
  ["stop-apas", 1],
  ["stop-itpark", 2],
  ["stop-ayala", 3],
  ["stop-usc-main", 4],
  ["stop-colon", 5],
  ["stop-carbon", 6],
].map(([stopId, stopOrder], index) => ({
  id: `variant-stop-${index + 1}`,
  variant_id: "variant-17b",
  stop_id: stopId as string,
  stop_order: stopOrder as number,
  is_pickup: true,
  is_dropoff: true,
  raw_text: null,
  source_section: "test",
  created_at: "2026-04-20T00:00:00.000Z",
}));

export function buildResolver() {
  return createPlaceResolver(routeRows, aliasRows, placeRows);
}
